### ISSUE TITLE
Getting different Gamlers Fever Dream outcome in the game

### ISSUE THREAD

**Issue by brankodencic** [Joseph3079/FtHoF-Planner-v5#2]
Hello :)
This is probably the edge case, but wondering if you could figure out why its happening?
With this save, when I cast Gamblers Fever Dream, i get Cursed Fingers, but if I add more wizrd towers, then it changes to Stretch time.
If its worth anything, "Fortune cookie" steam mod is predicting it correctly in this case.
I tried changing all the settings on your planner to replicate the scenario but with no luck.

`Mi4wNTJ8fDE3MTU0NjIwOTI2MDQ7MTcxNDUwNjcxNzc0ODsxNzE1NTU0MTQwOTU0O1N2ZW5zIENvb2tpZXM7bnpvcnc7MCw0LDksNCw5LDI4LDN8MDExMTAxMDAxMDAxMDExMDAwMDEwMTAxMDAxfDEuMDU4NTU0NDU0MTg5ODE5NGUrNjY7My4xMjA3ODI5ODAzNjY3NjNlKzY3OzEzNzE1NDsyMDEzOzMuMTIwNzI2MTQ4NTkxMzE0ZSs2NzsyMTc7MTsyOzUuOTI4MTc5MTE2MzIwMjQ0ZSs2NTswOzE7MDswOy0xOzg7MTEwOzEuMDIwODg5MjU0NjUzMjg3ZSs2MDs0MDsxNDsxNTsyMjY2NDI3OzExO3ZhbGVudGluZXM7MDswOzg0MDA1MzgwOTY4MjE4NTUwMDs3NjUxMTU2NjQ2MTc1Mzc4MDA7NzQ5MzgxNDUwNjQ2NDc1ODA7MDswOzIyMjsyMjY7NjM5OzY0MTs4NjU7Mjc7MTU7MjA7MjswOzA7MDsxOzE0OzE3MTU1MTg5NzM5MTg7MDswOzsxMDA7MTsxOzEuMDc1MTM3NzI4MDM1OTkyMmUrNTY7MDswOzA7fDEwNjAsMTQxMSw3LjMxMzU4NTgxODU0Mzk5NmUrNjEsMCwsMCwxMDYwOzEwNTAsNTE0MCw1LjA2MzczNzgyMzEwMDc5ZSs2MCwwLCwwLDEwNTA7MTAyMCw1OTQwLDMuMDM2NTIyNzQ1MDI3NjQ3NmUrNTksNCwxNzE1NTU0NDM0NTQ2OjQ6MTcxNTU0MDkzOTYyMjowOjI6NzI6MTowOjE3MTU0NjIwOTI2MTQ6IDExMTExMDEwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6NTo5MzowOjA6MDowOjA6MDo1Ojg4OjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDo1OjkxOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6LDAsMTAyMDsxMDAwLDc4ODAsNy4xMjQ1OTE5NDE0MTM4NGUrNTksMCwsMCwxMDAwOzk4MCw3NTkwLDMuODE2MDg4ODEzNjgyMDE3N2UrNTksMCwsMCw5ODA7OTYwLDc0MDAsNC40NTYyNzY2NzkyNzAxMDA3ZSs1OCwxLDA6MTA0OjE6LTEyMzg1NTkuNDIzNDI4NjY1ODoxOiAzNzIxOjU6MjEwOjQwMjoxMDUwOjA6MDoyNjEwITQ0NjoyOi01OToyOToxMDAwOjA6MDo2ODMhNDE0MzozOjE3NTo0ODE6OTcwOjA6MDo0MTE4ITEzNDM6NTozODE6OTY6OTcwOjA6MDo1MTExITUzNzU6Mzo0NzA6MzQyOjk1MDowOjA6MTAwITY2OToxOi00OjQ0NDo4NTc6MDowOjI1MzQhNjM4OjU6OTA6NDQwOjkwMDowOjA6MjMwOSE4NjM2OjU6NzI6MzU1Ojg5MDowOjA6NTUxNCE3NjgyOjU6MTc6MTg3Ojg1MDowOjA6NTcyNiE3ODQ6NTotMTQwOjEwMTo4MDA6MDowOjI3OTQhOTMyOjA6LTEwMTozNDk6ODMwOjA6MDoxMzIwOSE1MTc1OjI6LTMzNjoxNzE6ODEwOjA6MDo2NDE3ITg4NTk6MTozNjoxODg6NzkwOjA6MDoxMjkzNiEzNTU5OjU6LTUyOjI4Mzo3NzA6MDowOjg1NTEhMTE3MzE6MTo3MDozMzI6NzUwOjA6MDoxMjgyNSExODIxOjU6LTE2MDo2MDo3MDA6MDowOjY5MjIhMTYwNTY6NTotNDY0OjM1Nzo2NjA6MDowOjEzNzg0ITI1ODU6NTo0NDoyODg6NjMwOjA6MDoyMTE0NSEgMCwwLDk2MDs5NDAsODIwMiw0LjQ3ODU3MDQ5MDY3NjAxNWUrNjAsMSwyLzgvNiAzIDE3MTU1MzE3NzQzNjcgMCwwLDk1MDsxMiwzNTU4LDEuOTEyNzcxMjUxMDU0NTQ3OGUrNTcsMSwxNyAzNCAyMzEgMSwwLDg0Nzs5MDAsNDUzMCwyLjcxMDYyNjEyOTgwNTUwMThlKzU3LDAsLDAsOTAwOzg5MCw0NDgwLDUuMzA3ODk4ODg0MzkyNTc3NGUrNTcsMCwsMCw4OTA7ODcwLDQzNTAsMS41MzI5MDg4ODcxMzM5ODg0ZSs2MCwwLCwwLDg3MDs4NTAsNDI4MCw1LjA0MzY4MzIxNjg2OTAxNWUrNjAsMCwsMCw4NTA7ODMwLDQxOTAsOC40ODUyNTE1MzY3NjM5NzllKzU5LDAsLDAsODMwOzgxMCwzMzEwLDMuMjM1NzU0MTAxMjczMjg4ZSs2MCwwLCwwLDgxMDs4MDAsMjU4MCw4LjIzMzk2MzU3NTY3OTgxZSs2MCwwLCwwLDgwMDs3OTAsMTE0MCw1Ljk1MjM1MzEzMTUwMzM0NWUrNjEsMCwsMCw3OTA7NzUwLDE4NTAsMS45NjQzNDA1MDIzMTYxMmUrNjIsMCwsMCw3NTA7NzEwLDE3NjAsMS41NTE0NzQxNTk4Mzk0Mjc4ZSs2MSwwLCwwLDcxMDs2NzAsMTY4MCw0LjczMDY2ODQwMjYxODc2MjRlKzYxLDAsLDAsNjcwOzY1MCwxMDAzLDguNzMxNzQxODU3OTE3NzAzZSs2MSwwLCwwLDY1MDt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTEwMDExMTExMTAwMTExMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMTEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTEwMDExMTExMTExMTExMTEwMTAwMDAwMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTEwMTAxMTExMDExMTExMTAxMDAwMDAwMTExMTExMTAxMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMDExMDEwMDExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTAwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTEwMDAwMDExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTAxMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMDAxMDExMDAxMTEwMTAxMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTAwMDAxMTExfHxDQ1NFOnsidmVyc2lvbiI6IjIuMDM1IiwiQWNoaWV2ZW1lbnRzIjp7fSwiVXBncmFkZXMiOnt9LCJCdWlsZGluZ3MiOnt9LCJCdWZmcyI6e30sIlNlYXNvbnMiOnt9LCJPdGhlck1vZHMiOnt9LCJ2YXVsdCI6W10sInBlcm1hbmVudFVwZ3JhZGVzIjpbLTEsLTEsLTEsLTEsLTFdLCJjaGltZVR5cGUiOiJGb3J0dW5lIiwibWlsa1R5cGUiOiJBdXRvbWF0aWMiLCJiZ1R5cGUiOiJBdXRvbWF0aWMiLCJzaG93VmVyc2lvbk5vIjoxfTtGb3J0dW5lIENvb2tpZTp7InNwZWxsRm9yZWNhc3RMZW5ndGgiOjEwLCJzaW1HQ3MiOjAsImNvbG9yT3ZlcnJpZGUiOnsiQnVpbGRpbmcgU3BlY2lhbCI6IiNGRjAwRkYiLCJDbGljayBGcmVuenkiOiIjNEJCOEYwIiwiRWxkZXIgRnJlbnp5IjoiI0UxQzY5OSIsIkZyZWUgU3VnYXIgTHVtcCI6IiNEQUE1NjAifSwiZm9yZWNhc3REcmFnb25Ecm9wIjp0cnVlfTtNRVRBOipjb29sZXIgc2FtcGxlIG1vZCwqbGFuZyBzYW1wbGUgbW9kLCpzYW1wbGUgbW9kLENDU0UsRm9ydHVuZSBDb29raWUsY3BtLHNhdmUgdG8gZmlsZTs%3D%21END%21`

**Comment by Joseph3079** [comment]
This is caused by you not having enough magic to afford every possible spell from GFD. With a random seed of 0.2579, if all 8 spells are available the game would choose the 3rd spell (Stretch Time), since the game assigns each spell an equal length range, so 0-0.125 is conjure baked goods, 0.125-0.25 is FtHoF, and 0.25-0.375 is stretch time. With only 17 max magic, you cannot afford GFD Spontaneous Edifice, since it costs 3+14.5, so there are only 7 eligible spells. That would mean conjure baked goods would be chosen from 0-0.1429 and FtHoF would be chosen from 0.1429-0.2857, so you would instead get a FtHoF cookie instead. If you buy more towers, you would no longer be able to afford GFD FtHoF, so there are only 6 eligible spells, and the 2nd one is stretch time. I haven't bothered to add a setting to change current or max magic, since most people either don't know enough about this to manipulate the seeding to their advantage, or they just use the displayed random seed to manually calculate what spell GFD would give at that point.

**Comment by brankodencic** [comment]
Thank you very much for explanation, you rock. I can see some nice potential advantage of this info, like utilizing it to maybe add additional spell to the combo which planner shows, once i have sugar lumps to spend on refills. If you know of a tool that would allow me to see what magic it would choose with such low mana, please let me know :)
